export const  SET_TEXT_FILTER = "SET_TEXT_FILTER"
export const SET_CHECKBOX_FILTER ='SET_CHECKBOX_FILTER'
export const REMOVE_CHECKBOX_FILTER ='REMOVE_CHECKBOX_FILTER'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const SET_FILTER_LIST= 'SET_FILTER_LIST'